name: "Adjust API Properties"
description: "Zips API folders and uploads them to Artifactory"

inputs:
  config-file:
    description: "Path to deployment YAML"
    required: true
  build-path:
    description: "Unique build directory path"
    required: true

runs:
  using: "composite"
  steps:
    - name: Adjust API Properties
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.vaultPath }}" "${{ inputs.server }}"
      # env:
      #   ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
      #   ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
