name: 'Logout to APIC Gateway'
description: 'logout to APIC'
inputs:
 server:
    description: 'server you want to login'
    default: 'api-manager-ui.apicv10dev.adib.co.ae'

runs:
  using: 'composite'
  steps:
    - name: Run login logic
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.server }}"
