name: Import All UDP Policies
description: Loops over APIs and imports UDPs
inputs:
  configFile:
    required: true
  packageDir:
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -e
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.configFile }}" "${{ inputs.packageDir }}" "${{ github.workspace }}"
