name: 'Extract API Packages'
description: 'Downloads and unzips packages for each API based on org type'
inputs:
  configFile:
    description: 'Path to the UAT deployment config YAML'
    required: true
  packageDir:
    description: 'Workspace build directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Extract API Packages
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/entrypoint.sh"
        "${{ github.action_path }}/entrypoint.sh" "${{ inputs.configFile }}" "${{ inputs.packageDir }}"
