name: SSH Without Docker

on:
  workflow_dispatch:

jobs:
  ssh-job:
    runs-on: test-run

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH using password (local self-hosted runner)
        run: |
          sshpass -p "Neon3476234762@@@@" ssh -o StrictHostKeyChecking=no hamza.asad@192.168.76.18 "hostname && uptime"
