name: SSH Without Docker

on:
  workflow_dispatch:

jobs:
  ssh-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH into Host via password
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: 192.168.76.18
          username: hamza.asad
          password: Neon3476234762@@@@
          command: |
            echo "✅ Connected to host"
            uname -a
            uptime
