name: SSH to Host Machine

on:
  workflow_dispatch:

jobs:
  ssh-job:
    runs-on: test-run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SSH into Host and Run Command
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 172.17.0.1
          username: hamza.asad
          password: Neon3476243762@@@@
          port: 22
          script: |
            echo "✅ Connected to host machine"
            hostname
            whoami
